1. Import the numpy package under the alias np.

In [ ]:
import numpy as np          #numpy import

2. Print the numpy version and the configuration.

In [ ]:
print(np.__version__)       #numpy version
print(np.show_config())     #numpy configuration

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

3. Create a null vector (an array) of size 5.

In [ ]:
array = np.zeros(5)       #create a null verctor
print(array)

[0. 0. 0. 0. 0.]


4. Create an identity matrix of size 10 and print its memory size which needed to store it on the
computer memory.

In [ ]:
array = np.eye(10)
print(array)           #matrix of size 10
print(array.shape)     #memory size

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
(10, 10)


5. Create a vector with values ranging from 0 to 255.

In [ ]:
array = np.arange(256)         #value ranging from 0 to 255
print(array)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

6. Create a vector to store the values: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9. Then reverse the vector in such a
way that the first element becomes the last element in the reversed array.

In [ ]:
array = np.arange(10)      # store the value
print(array)
array1 = array[::-1]       #reverse stored value
print(array1)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


7. Create a 5 x 5 matrix with values ranging from 0 to 10.

In [ ]:
array = np.random.uniform(low=0, high=10, size=(5,5))
print(array)


[[5.24479551 8.29908933 6.60027558 5.60548723 6.54847609]
 [3.9505564  4.78117277 5.97101325 3.81408311 7.23844255]
 [1.08816242 4.65220871 4.2874058  5.98505    3.43621971]
 [1.98948209 6.31417818 2.01512934 3.8799491  3.57104474]
 [8.0530412  9.78282224 0.48580073 0.36011024 5.15011867]]


Create a vector to store the following values: 19, 12, 0, -5, 0, 4, -6.

In [5]:
import numpy as np
array = np.array([19, 12, 0, -5, 0, 4, -6])
print(array)


[19 12  0 -5  0  4 -6]


a. Print the index value for -5.

In [6]:
index= np.where(array == -5)
print(index)

(array([3]),)


b. Print the indices of non-zero values.

In [7]:
index = np.where(array != 0)
print( index)

(array([0, 1, 3, 5, 6]),)


c. Find the minimum and maximum values.

In [8]:
maxivalue = np.max(array)
minivalue = np.min(array)
print("The maximum value :", maxivalue)
print("The minimum value :", minivalue)

The maximum value : 19
The minimum value : -6


9. Create an 8 x 8 matrix with 0s on the border and 1s inside (Hint: using the knowledge
acquired from array slicing).

In [ ]:
array = np.ones((8,8))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Create the following 6 x 6 matrix given below.

In [ ]:
array = np.array([[12, 4, 6, 0, 55, 6], [19, 7, 0, 1, 8, 0], [99, 12, 3, 4, 2, 32], [6, 1, 23, 0, 45, 54], [78, 0, 156, 124, 7, 73], [0, 41, 0, 7, 6, 21]])
print( array)

[[ 12   4   6   0  55   6]
 [ 19   7   0   1   8   0]
 [ 99  12   3   4   2  32]
 [  6   1  23   0  45  54]
 [ 78   0 156 124   7  73]
 [  0  41   0   7   6  21]]


a. What is normalization?

The normalization is an array as an input, normalizes the values of the array in the range of 0 to 1 by using some formula, and provides the normalized array as an output.

b. What are the advantages of normalization in arrays?

A more modest information base can be kept ,
tables are narrowed ,
It has easy understanable format


c. Get the normalized matrix for the above matrix.

In [ ]:
normalize = np.linalg.norm(array)
array1 = array/normalize
print( array1)

[[0.04422718 0.01474239 0.02211359 0.         0.2027079  0.02211359]
 [0.07002637 0.02579919 0.         0.0036856  0.02948479 0.        ]
 [0.36487423 0.04422718 0.01105679 0.01474239 0.0073712  0.11793914]
 [0.02211359 0.0036856  0.08476876 0.         0.16585192 0.19902231]
 [0.28747666 0.         0.57495333 0.45701418 0.02579919 0.26904867]
 [0.         0.15110953 0.         0.02579919 0.02211359 0.07739756]]


d. Reshape the array to (4, 9).

In [ ]:
array = array1.reshape(4, 9)
print( array)

[[0.04422718 0.01474239 0.02211359 0.         0.2027079  0.02211359
  0.07002637 0.02579919 0.        ]
 [0.0036856  0.02948479 0.         0.36487423 0.04422718 0.01105679
  0.01474239 0.0073712  0.11793914]
 [0.02211359 0.0036856  0.08476876 0.         0.16585192 0.19902231
  0.28747666 0.         0.57495333]
 [0.45701418 0.02579919 0.26904867 0.         0.15110953 0.
  0.02579919 0.02211359 0.07739756]]


11. What are the results of the following two statements?
a. print(np.array(0) / np.array(0)).

In [ ]:
print( np.array(0) / np.array(0))

nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


b. print(np.array(0) // np.array(0)).

In [ ]:
print(np.array(0) // np.array(0))



0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [ ]:
c. Explain the output you got from both statements.
 np.array(0)/np.array(0) gives a float output ,but np.array(0) // np.array(0)) gives the rounded integer value as output.


12. How to get the dates of the day before yesterday, yesterday, today and tomorrow? (Hint: the
date should be a variable).

In [9]:
import datetime 
today = datetime.date.today()
day_before_yesterday = today - datetime.timedelta(days = 2)
yesterday = today - datetime.timedelta(days = 1) 
tomorrow = today + datetime.timedelta(days = 1)
print('Day before Yesterday : ', day_before_yesterday)
print('Yesterday : ', yesterday)
print('Today : ', today)
print('Tomorrow : ', tomorrow)


Day before Yesterday :  2022-07-19
Yesterday :  2022-07-20
Today :  2022-07-21
Tomorrow :  2022-07-22


13. Create a random vector of size 15 with values ranging from 0 to 50. Then sort the array.

In [ ]:
array = np.random.uniform(51, size=(15))
print(array)
array1 = np.sort(array)
print(array1)


[26.31215042 40.81884269 19.57184859  3.88811725 46.03797438 39.38399627
  9.11953775 43.07350775 30.7478946  24.11349448 22.60372235 28.44054028
 10.8727333  36.05325544 21.26941355]
[ 3.88811725  9.11953775 10.8727333  19.57184859 21.26941355 22.60372235
 24.11349448 26.31215042 28.44054028 30.7478946  36.05325544 39.38399627
 40.81884269 43.07350775 46.03797438]


14. Create two random arrays P and Q and check whether they are equal or not.

In [ ]:
arrayP = np.random.random()
arrayQ = np.random.random()
print(arrayP)
print(arrayQ)
if arrayP == arrayQ:
  print("P and Q arrays are eqal")
else:
  print("P and Q arrays are not eqal")

0.20238708695427754
0.030324110591380737
P and Q arrays are not eqal


15. Implement a program (Currency Convertor App) to convert following currencies; United
States Dollar (USD), Euro (EUR) and Pound sterling (GBP) to Sri Lankan Rupees (SLR)
using the knowledge you gained from the first and second sessions. In this case, you have to
get the currency type and the amount as user inputs. (Hint: latest currency rates can be found
on the internet).

In [ ]:
while True:
  #  user input
  print("Select the currency you want to convert to to Sri Lankan Rupees (SLR) :")
  print("1. United States Dollar (USD)")
  print("2. Euro (EUR)")
  print("3. Pound sterling (GBP)")
  choice = input("Enter your choice(1/2/3): ")

# check if choice is one of the three options
  if choice in ('1', '2', '3'):
  
    if choice == '1':
     usd = float(input ("Enter amount of United States Dollars (USD) you want to convert to Sri Lankan Rupees (SLR): "))
     usd_to_slr = 359.62
     slr = usd * usd_to_slr
     print("$ %.2f = Rs. %.2f" % (usd, slr))
    
    elif choice == '2':
      eur = float(input ("Enter amount of Euros (EUR) you want to convert to Sri Lankan Rupees (SLR): "))
      eur_to_slr = 367.98
      slr = eur * eur_to_slr
      print("€ %.2f = Rs. %.2f" % (eur, slr))
      
    elif choice == '3':
      gbp = float(input ("Enter amount of Pounds sterling (GBP) you want to convert to Sri Lankan Rupees (SLR): "))
      gbp_to_slr = 431.28
      slr = gbp * gbp_to_slr
      print("£ %.2f = Rs. %.2f" % (gbp, slr))

Select the currency you want to convert to to Sri Lankan Rupees (SLR) :
1. United States Dollar (USD)
2. Euro (EUR)
3. Pound sterling (GBP)
Enter your choice(1/2/3): 1
Enter amount of United States Dollars (USD) you want to convert to Sri Lankan Rupees (SLR): 1
$ 1.00 = Rs. 359.62
Select the currency you want to convert to to Sri Lankan Rupees (SLR) :
1. United States Dollar (USD)
2. Euro (EUR)
3. Pound sterling (GBP)
Enter your choice(1/2/3): 2
Enter amount of Euros (EUR) you want to convert to Sri Lankan Rupees (SLR): 1
€ 1.00 = Rs. 367.98
Select the currency you want to convert to to Sri Lankan Rupees (SLR) :
1. United States Dollar (USD)
2. Euro (EUR)
3. Pound sterling (GBP)
Enter your choice(1/2/3): 3
Enter amount of Pounds sterling (GBP) you want to convert to Sri Lankan Rupees (SLR): 1
£ 1.00 = Rs. 431.28
Select the currency you want to convert to to Sri Lankan Rupees (SLR) :
1. United States Dollar (USD)
2. Euro (EUR)
3. Pound sterling (GBP)
